import "./globals.css";
import { Instrument_Sans, Margarine } from "next/font/google";

const margarine = Margarine({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  style: "normal",
  fallback: ["sans-serif"],
  variable: "--margarine",
});

const instrument_sans = Instrument_Sans({
  weight: ["500"],
  subsets: ["latin"],
  style: "normal",
  display: "swap",
  fallback: ["sans-serif"],
  variable: "--instrument_sans",
});

export const metadata = {
  title: "PlayPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${margarine.variable} ${instrument_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
